### ISSUE TITLE
exe_bin文件夹下的文件是用什么写的呢 或者来源是？

### ISSUE THREAD

**Issue by lichenghuan** [loveyu/nodejs-clipboard-listener-sync-on-windows#1]
ClipBoardListener_x64.exe
ClipboardPasteImage_x64.exe
clipboard_x86_64.exe
这三个是用什么写的呢 或来源是？

还有，为什么我复制任何图片，返回的都是null呢

**Comment by loveyu** [comment]
c++ 写的剪贴板监听工具，有一些来自于第三方，有一个是自己写的。
自己写的参考： https://github.com/loveyu/WindowsClipboardConsoleListener
第三方：https://github.com/sindresorhus/clipboardy/tree/master/fallbacks/windows

**Comment by lichenghuan** [comment]
> c++ 写的剪贴板监听工具，有一些来自于第三方，有一个是自己写的。
> 自己写的参考： https://github.com/loveyu/WindowsClipboardConsoleListener
> 第三方：https://github.com/sindresorhus/clipboardy/tree/master/fallbacks/windows

不太会用c++ ，  c++的里面是轮询获取剪切板数据吗

**Comment by loveyu** [comment]
监听Windows消息事件，非轮询

**Comment by lichenghuan** [comment]
> 监听Windows消息事件，非轮询

node.js的话，没找到有监听windows的剪切板消息

**Comment by loveyu** [comment]
> > 监听Windows消息事件，非轮询
> 
> node.js的话，没找到有监听windows的剪切板消息

通过exe进行事件监听，然后通过进程管道IO输出给nodejs，以达到监听的目的 
https://github.com/loveyu/nodejs-clipboard-listener-sync-on-windows/blob/master/lib/ClipboardEvent.js#L51

**Comment by lichenghuan** [comment]
> > > 监听Windows消息事件，非轮询
> > 
> > 
> > node.js的话，没找到有监听windows的剪切板消息
> 
> 通过exe进行事件监听，然后通过进程管道IO输出给nodejs，以达到监听的目的
> https://github.com/loveyu/nodejs-clipboard-listener-sync-on-windows/blob/master/lib/ClipboardEvent.js#L51

明白，谢谢
